import Head from 'next/head'
import Image from 'next/image'
import Hero from '../hero'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from "react";

export default function Home() {
  const [cities, setCities] = useState();
  const [selectedCity, setSelectedCity] = useState("Tokyo");
  const [weather, setWeather] = useState();

  const handleClick = (name) => {
    setSelectedCity(name);
  };

  useEffect(() => {
    fetch("https://countriesnow.space/api/v0.1/countries/capital/")
      .then((response) => response.json())
      .then((response) => {
        setCities(response);
      })
      .catch((err) => console.error(err));
    // console.log(cities);
  }, []);

  useEffect(() => {
    fetch(
      `http://api.weatherstack.com/current?access_key=f61f971da2cb187062dd98fe9f6c7b42&query=${selectedCity}`
    )
      .then((response) => response.json())
      .then((response) => {
        console.log(response);
        setWeather(response);
      })
      .catch((err) => console.error(err));
    console.log(weather);
  }, [selectedCity]);

  if (!cities || !weather) {
    return <div>Loading...</div>;
  }
  console.log(weather);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <Hero cities={cities} weather={weather} handleClick={handleClick} />
      </main>
      
    </div>
  )
}
